Make 'shared-dir' a required argument
To make 'clap' even more helpful when it comes to starting up the
process:

	$ ./target/debug/virtiofsd-rs
	error: The following required arguments were not provided:
	    --shared-dir <shared-dir>
	    --socket <socket>

	USAGE:
	    virtiofsd-rs --seccomp <seccomp> --shared-dir <shared-dir> --socket <socket>

	For more information try --help

Signed-off-by: Connor Kuehl <ckuehl@redhat.com>