Make 'socket' a required argument
This will allow 'clap' to generate a helpful error message for the
user instead of having the application panic:

	$ cargo run
	error: The following required arguments were not provided:
	    --socket <socket>

	USAGE:
	    virtiofsd-rs --seccomp <seccomp> --socket <socket>

	For more information try --help

Signed-off-by: Connor Kuehl <ckuehl@redhat.com>